##################################################################################
#####                          MinimizedProject                              #####
##################################################################################
MinimizedProject:
  path: data/project/
  properties:
    name: String
    appIconUrl: String
    publisher:
      type: String
      ignore: true

##################################################################################
#####                              Project                                   #####
##################################################################################
Project:
  path: data/project/
  properties:
    name: String
    description: String
    publisher: String?
    developers:
      type: array
      items:
        type: MinimizedDeveloper
      required: false
      non_final: true
    releaseData: DateTime
    links: ProjectLinks?
    images:
      type: ProjectImages
      required: false
      non_final: true

ProjectLinks:
  path: data/project/
  properties:
    appstore: String?
    playstore: String?
    website: String?
    youTube: String?
    demoYouTubeVideo: String?

ProjectImages:
  path: data/project/
  properties:
    appIconUrl: String
    companyLogoUrl: String?
    bannerUrl: String?
    screenshotUrls: List<String>

##################################################################################
#####                              Company                                   #####
##################################################################################
MinimizedCompany:
  path: data/company/
  properties:
    name: String
    logoUrl: String
    useLogoInsteadOfTextTitle: boolean

Company:
  path: data/company/
  properties:
    name: String
    description: String?
    useLogoInsteadOfTextTitle:
      type: boolean
      required: true
      default_value: false
    links: CompanyLinks?
    developers: List<MinimizedDeveloper>?
    projects:
      type: array
      items:
        type: MinimizedProject
      required: false
      non_final: true
    images:
      type: CompanyImages
      required: false
      non_final: true

CompanyLinks:
  path: data/company/
  properties:
    website: String

CompanyImages:
  path: data/company/
  properties:
    logoUrl: String

##################################################################################
#####                             Developer                                  #####
##################################################################################
MinimizedDeveloper:
  path: data/developer/
  properties:
    githubUserName: String
    name:
      type: String
      required: false
      non_final: true
    profilePictureUrl:
      type: String
      required: false
      non_final: true


Developer:
  path: data/developer/
  properties:
    githubUserName: String
    name: String?
    description: String?
    links: DeveloperLinks?
    projects:
      type: array
      items:
        type: MinimizedProject
      required: false
      non_final: true
    images:
      type: DeveloperImages
      required: false
      non_final: true

DeveloperLinks:
  path: data/developer/
  properties:
    linkedin: String?
    personalWebsite: String?
    freelanceWebsite: String?

DeveloperImages:
  path: data/developer/
  properties:
    profilePictureUrl: String
