name: api_deploy
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  json_annotation: ^4.8.0
  path: ^1.8.0
  api_validate:
    path: ../api_validate
  made_in_flutter_belgium_data:
    path: ../made_in_flutter_belgium_data

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  model_generator: 6.2.1

model_generator:
  base_directory: src/model