on:
  issues:
    types: [opened]
  pull_request:
    branches:
      - main    

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./scripts/labels.js')
            await script({github, context, core})